"""initial_enterprise_schema

Revision ID: 79fe52646d51
Revises: 
Create Date: 2026-09-24 16:36:09.940532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79fe52646d51'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_students_id'))
        batch_op.drop_index(batch_op.f('ix_parent_students_parent_user_id'))
        batch_op.drop_index(batch_op.f('ix_parent_students_student_id'))

    op.drop_table('parent_students')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('school_payment_configs', schema=None) as batch_op:
        batch_op.drop_column('payment_instructions')

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.alter_column('is_suspended',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('max_students',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(500)'))
        batch_op.alter_column('max_teachers',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(50)'))
        batch_op.alter_column('subscription_plan',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'starter'"))
        batch_op.alter_column('parent_profile_approval_required',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.create_index(batch_op.f('ix_schools_code'), ['code'], unique=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('timetable_slots', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('must_reset_password',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('allow_whatsapp',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('allow_email',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('allow_sms',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('allow_sms',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('allow_email',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('allow_whatsapp',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('must_reset_password',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('timetable_slots', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('students', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schools_code'))
        batch_op.alter_column('parent_profile_approval_required',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('subscription_plan',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'starter'"))
        batch_op.alter_column('max_teachers',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(50)'))
        batch_op.alter_column('max_students',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(500)'))
        batch_op.alter_column('is_suspended',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('school_payment_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_instructions', sa.TEXT(), nullable=True))

    with op.batch_alter_table('homework', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('parent_students',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('parent_user_id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_user_id', 'student_id', name=op.f('uq_parent_student'))
    )
    with op.batch_alter_table('parent_students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_students_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_students_parent_user_id'), ['parent_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_students_id'), ['id'], unique=False)

    # ### end Alembic commands ###
